import { Canvas, useFrame } from '@react-three/fiber'
import { Environment, Text } from '@react-three/drei'
import { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'

const exhibits=[
 {id:'portrait',title:'Khu trưng bày hình ảnh',description:'Nơi giới thiệu hình ảnh, tư liệu và những dấu mốc tiêu biểu về Chủ tịch Hồ Chí Minh.',position:[-4.6,2.05,-5.72]},
 {id:'books',title:'Góc sách',description:'Không gian giới thiệu sách, tài liệu và các tác phẩm viết về tư tưởng, đạo đức, phong cách Hồ Chí Minh.',position:[4.6,2.05,-5.72]},
 {id:'video',title:'Màn hình tư liệu',description:'Có thể gắn video tư liệu, phóng sự hoặc sản phẩm học tập của học sinh tại đây.',position:[0,2.15,-5.7]}
]

function Room(){return <group>
 <mesh position={[0,-.15,0]} receiveShadow><boxGeometry args={[18,.3,14]}/><meshStandardMaterial color="#7c5a3c"/></mesh>
 <mesh position={[0,4.5,-6]} receiveShadow><boxGeometry args={[18,9,.3]}/><meshStandardMaterial color="#eee4d3"/></mesh>
 <mesh position={[-9,2.25,0]} receiveShadow><boxGeometry args={[.3,4.5,12]}/><meshStandardMaterial color="#d9c6aa"/></mesh>
 <mesh position={[9,2.25,0]} receiveShadow><boxGeometry args={[.3,4.5,12]}/><meshStandardMaterial color="#d9c6aa"/></mesh>
 <mesh position={[0,4.5,0]}><boxGeometry args={[18,.3,12]}/><meshStandardMaterial color="#e7dccb"/></mesh>
 <Text position={[0,3.75,-5.78]} fontSize={.48} color="#7a1f1f" anchorX="center">KHÔNG GIAN VĂN HÓA HỒ CHÍ MINH</Text>
 <Text position={[0,3.25,-5.78]} fontSize={.19} color="#5d554b" anchorX="center">Học tập • Trải nghiệm • Lan tỏa giá trị văn hóa</Text>
 <ExhibitFrame position={[-4.6,2.05,-5.72]} label="ẢNH TƯ LIỆU"/>
 <ExhibitFrame position={[4.6,2.05,-5.72]} label="SÁCH & TƯ LIỆU"/>
 <VideoScreen position={[0,2.15,-5.7]}/>
 <Bookshelf position={[6.6,1.35,-3.8]}/><Plant position={[-6.7,.9,-3.8]}/><Plant position={[7,.9,2.4]}/><Desk position={[-5.9,.7,2.4]}/><DisplayCase position={[0,.65,-2.7]}/>
 </group>}
function ExhibitFrame({position,label}){return <group position={position}><mesh castShadow><boxGeometry args={[3.68,2.43,.12]}/><meshStandardMaterial color="#5b3a20"/></mesh><mesh position={[0,0,.08]}><planeGeometry args={[3.5,2.25]}/><meshStandardMaterial color="#d9d1c5"/></mesh><Text position={[0,0,.15]} fontSize={.28} color="#7a1f1f" anchorX="center">{label}</Text></group>}
function VideoScreen({position}){return <group position={position}><mesh castShadow><boxGeometry args={[4.35,2.5,.16]}/><meshStandardMaterial color="#222"/></mesh><mesh position={[0,0,.11]}><planeGeometry args={[4.05,2.2]}/><meshStandardMaterial color="#1d3557"/></mesh><Text position={[0,.2,.18]} fontSize={.3} color="white" anchorX="center">MÀN HÌNH TƯ LIỆU</Text><Text position={[0,-.25,.18]} fontSize={.16} color="#dce7f5" anchorX="center">Đến gần để xem</Text></group>}
function Bookshelf({position}){return <group position={position}><mesh castShadow><boxGeometry args={[3.5,2.8,.5]}/><meshStandardMaterial color="#6d4528"/></mesh>{Array.from({length:14},(_,i)=><mesh key={i} position={[(i%7)*.48-1.45,Math.floor(i/7)*.82-.1,.31]} castShadow><boxGeometry args={[.34,.62+(i%3)*.08,.13]}/><meshStandardMaterial color={['#9b3d35','#d2a84a','#345c55','#5a4b7c'][i%4]}/></mesh>)}</group>}
function Plant({position}){return <group position={position}><mesh position={[0,.35,0]} castShadow><cylinderGeometry args={[.42,.55,.7,20]}/><meshStandardMaterial color="#b66d42"/></mesh><mesh position={[0,1.1,0]}><sphereGeometry args={[.75,16,12]}/><meshStandardMaterial color="#4f7f4d"/></mesh><mesh position={[.38,1.35,.12]} scale={[.65,.85,.65]}><sphereGeometry args={[.6,16,12]}/><meshStandardMaterial color="#638d50"/></mesh></group>}
function Desk({position}){return <group position={position}><mesh position={[0,.65,0]} castShadow><boxGeometry args={[3.2,.22,1.4]}/><meshStandardMaterial color="#704522"/></mesh>{[[-1.25,.3,-.48],[1.25,.3,-.48],[-1.25,.3,.48],[1.25,.3,.48]].map((p,i)=><mesh key={i} position={p}><boxGeometry args={[.16,.65,.16]}/><meshStandardMaterial color="#513018"/></mesh>)}</group>}
function DisplayCase({position}){return <group position={position}><mesh castShadow><boxGeometry args={[3.2,1.25,1.7]}/><meshStandardMaterial color="#8a6a4a"/></mesh><mesh position={[0,1.05,0]} transparent opacity={.3}><boxGeometry args={[3,.7,1.5]}/><meshPhysicalMaterial transmission={.2} roughness={.1} transparent opacity={.35}/></mesh></group>}

function Character({onNear}){const ref=useRef();const keys=useRef({});const [moving,setMoving]=useState(false)
 useEffect(()=>{const d=e=>keys.current[e.key.toLowerCase()]=true,u=e=>keys.current[e.key.toLowerCase()]=false;addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[])
 useFrame((state,delta)=>{if(!ref.current)return;const k=keys.current;let x=0,z=0;if(k.w||k.arrowup)z-=1;if(k.s||k.arrowdown)z+=1;if(k.a||k.arrowleft)x-=1;if(k.d||k.arrowright)x+=1;const go=x!==0||z!==0;setMoving(go);if(go){const l=Math.hypot(x,z);x/=l;z/=l;ref.current.position.x=THREE.MathUtils.clamp(ref.current.position.x+x*3.2*delta,-7.8,7.8);ref.current.position.z=THREE.MathUtils.clamp(ref.current.position.z+z*3.2*delta,-4.7,5);ref.current.rotation.y=Math.atan2(x,z)}ref.current.position.y=go?Math.sin(state.clock.elapsedTime*12)*.04:0;state.camera.position.lerp(new THREE.Vector3(ref.current.position.x,2.4,ref.current.position.z+4.2),1-Math.pow(.001,delta));state.camera.lookAt(ref.current.position.x,1,ref.current.position.z-1.2);const near=exhibits.map(e=>({...e,distance:Math.hypot(ref.current.position.x-e.position[0],ref.current.position.z-e.position[2])})).sort((a,b)=>a.distance-b.distance)[0];onNear(near.distance<2.7?near:null)})
 return <group ref={ref} position={[0,0,4]}><mesh castShadow position={[0,1.25,0]}><capsuleGeometry args={[.32,.75,8,16]}/><meshStandardMaterial color="#b43a2f"/></mesh><mesh castShadow position={[0,2.05,0]}><sphereGeometry args={[.34,20,20]}/><meshStandardMaterial color="#d5a47d"/></mesh><mesh castShadow position={[0,2.32,0]}><sphereGeometry args={[.37,20,12]}/><meshStandardMaterial color="#1e1b18"/></mesh>{moving&&<Text position={[0,2.9,0]} fontSize={.14} color="white" anchorX="center">Đang đi</Text>}</group>}

export default function App(){const[started,setStarted]=useState(false),[near,setNear]=useState(null),[selected,setSelected]=useState(null),[visitor,setVisitor]=useState({name:'',age:'',gender:''});const submit=e=>{e.preventDefault();if(visitor.name.trim())setStarted(true)};return <div className="app">
 {!started&&<div className="welcome"><div className="card"><div className="eyebrow">TRẢI NGHIỆM 3D</div><h1>Không gian văn hóa Hồ Chí Minh</h1><p>V1 — Phòng triển lãm 3D tương tác</p><form onSubmit={submit}><label>Tên hiển thị<input value={visitor.name} onChange={e=>setVisitor({...visitor,name:e.target.value})} placeholder="Ví dụ: Nguyễn An"/></label><div className="row"><label>Tuổi<input type="number" min="1" max="100" value={visitor.age} onChange={e=>setVisitor({...visitor,age:e.target.value})}/></label><label>Giới tính<select value={visitor.gender} onChange={e=>setVisitor({...visitor,gender:e.target.value})}><option value="">Chọn</option><option>Nam</option><option>Nữ</option><option>Khác</option><option>Không muốn trả lời</option></select></label></div><div className="note">Bản V1 chưa lưu thông tin lên máy chủ. Firebase sẽ được thêm ở bước sau.</div><button>Bắt đầu tham quan →</button></form></div></div>}
 {started&&<><div className="hud"><div><b>Không gian văn hóa Hồ Chí Minh</b><span>Xin chào, {visitor.name}</span></div><div className="controls"><b>WASD / ↑↓←→</b> Di chuyển</div></div><Canvas shadows camera={{position:[0,2.4,8],fov:55}}><color attach="background" args={['#b9c7d6']}/><ambientLight intensity={1.2}/><directionalLight castShadow position={[4,8,5]} intensity={2.2} shadow-mapSize-width={2048} shadow-mapSize-height={2048}/><pointLight position={[-4,3,0]} intensity={15} distance={12}/><Environment preset="city"/><Room/><Character onNear={setNear}/></Canvas><div className="bottom">👤 {visitor.name}　|　WASD hoặc phím mũi tên để di chuyển</div>{near&&<button className="interaction" onClick={()=>setSelected(near)}><small>ĐANG Ở GẦN</small><strong>{near.title}</strong><span>Nhấn để xem nội dung</span></button>}{selected&&<div className="backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="eyebrow">KHU TRƯNG BÀY</div><h2>{selected.title}</h2><p>{selected.description}</p><p className="note">Nội dung ảnh/video thật sẽ được thêm ở phiên bản tiếp theo.</p><button onClick={()=>setSelected(null)}>Đóng</button></div></div>}</>}
 </div>}
